Docker image with python and FastApi
tavobarrientos/RoleSynapse pull request #2
Opened 2024-12-13 23:03 UTC by crissins

This pull request introduces a Docker image for the Python FastAPI application, which is designed to be deployed on Azure as a container image. The changes include:

[Dockerfile](https://github.com/tavobarrientos/RoleSynapse/blob/Docker-Image/docker/Dockerfile): Dockerfile specifying the Python base image and the necessary dependencies for running the FastAPI application.

[app.py](https://github.com/tavobarrientos/RoleSynapse/blob/Docker-Image/docker/app.py): Sample FastAPI application is included in the Docker image, ensuring that the server is properly configured to run within the container environment.

[requirements.txt](https://github.com/tavobarrientos/RoleSynapse/blob/Docker-Image/docker/requirements.txt): Requirements file to ensure all necessary Python packages are installed when building the Docker image.

[docker-compose.yaml](https://github.com/tavobarrientos/RoleSynapse/blob/Docker-Image/docker/compose.yaml): Docker Compose configuration file is included to simplify the local setup and testing of the container.

This Docker image will serve as the base for deploying the FastAPI application on Azure's container services, ensuring seamless and efficient deployment.

2024-12-14 15:48 UTC, tavobarrientos requested changes

2024-12-14 15:48 UTC, tavobarrientos commented on docker/compose.yaml
renombralo a docker-compose.yaml

2024-12-14 22:19 UTC, crissins commented on docker/compose.yaml
Listo

2024-12-15 04:39 UTC, tavobarrientos approved these changes

2024-12-15 04:39 UTC, merged